In [1]:
import sqlite3
import pandas as pd

con = sqlite3.connect('hr_sample.sqlite')
pd.read_sql('SELECT name FROM sqlite_master WHERE type="table"', con)

        name
0  employees

In [162]:
df = pd.read_sql('''
    SELECT *
    FROM employees
''', con)
df

,report_date,employee_id,grade_num,position_name,unit_id_tree,person_surname,person_name,person_patronimics,gender,age_y,...,lead_experience_years,professionlevel_name,vac_days,lid_tribe_i_pernr,lid_1_lvl_i_pernr,lid_2_lvl_i_pernr,lid_3_lvl_i_pernr,lid_cluster_i_pernr,it_lid_cluster_i_pernr,cur_tribe_i_pernr
0,2025-10-31,10000001,13,HR-специалист,"[1063, 1103, 1107, 1108]",Гришина,Валерия,Алексеевна,F,25,...,0,Legal,19,10000145,10000028,10000145,10000145,10000145,10000145,10000145
1,2025-10-31,10000004,12,Юрист,"[1063, 1064, 1075, 1077]",Поляков,Евстафий,Федосеевич,M,57,...,0,Risk,20,10000134,10000028,10000134,10000323,10000323,10000323,10000134
2,2025-10-31,10000007,12,Специалист комплаенса,"[1115, 1138, 1139, 1144]",Сазонов,Валерий,Ильясович,M,30,...,5,Marketing,13,10000003,10000003,10000003,10000013,10000013,10000013,10000003
3,2025-10-31,10000018,9,Ведущий специалист по кредитованию,"[1235, 1236, 1246, 1248]",Белоусова,Тамара,Тарасовна,F,27,...,0,HR,11,10000324,10000049,10000324,10000346,10000324,10000324,10000324
4,2025-10-31,10000020,7,Финансовый аналитик,"[1063, 1064, 1065, 1067]",Самойлова,Анна,Альбертовна,F,46,...,0,Marketing,13,10000134,10000028,10000134,10000365,10000323,10000323,10000134
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28015,2026-03-31,10021477,8,Главный архитектор,"[1001, 1024, 1025, 1028]",Алексеев,Ерофей,Вилорович,M,38,...,0,Data,26,10000581,10000155,10000581,10002842,10000581,10000581,10000581
28016,2026-03-31,10021489,11,Ведущий специалист по продажам,"[1115, 1130, 1135, 1136]",Яковлев,Аристарх,Юльевич,M,25,...,0,HR,19,10000417,10000003,10000417,10000417,10000417,10000417,10000417
28017,2026-03-31,10021491,12,Специалист по кредитованию,"[1063, 1064, 1078, 1083]",Лыткина,Жанна,Богдановна,F,46,...,0,Risk,23,10000323,10000028,10000323,10000519,10000323,10000323,10000323
28018,2026-03-31,10021492,10,Кредитный аналитик,"[1063, 1084, 1085, 1087]",Маслова,Лидия,Егоровна,F,61,...,0,Operations,12,0,10000028,10000028,10000240,0,0,0
28019,2026-03-31,10021499,13,Ведущий специалист по кредитованию,"[1063, 1064, 1065, 1067]",Игнатьева,Фаина,Васильевна,F,40,...,0,Sales,9,10000323,10000028,10000323,10000365,10000323,10000323,10000323

In [168]:
df[df["employee_id"] == 10000145]#.shape

Empty DataFrame
Columns: [report_date, employee_id, grade_num, position_name, unit_id_tree, person_surname, person_name, person_patronimics, gender, age_y, wrk_email, ext_email, employee_kipphn, child_count, family_status, is_on_trial, sber_los_cnt_days, is_parental_leave, all_skills, date_since_salary_change_last, po_i_pernr, fp_res, fp_comp, full_oshs_name, all_succesors, children_gender, children_years, lang_with_level, tribe_name, cluster_name, team_name, tribe_code, cluster_code, team_code, all_goals_desc, mean_value_completion, num_goals, not_completed_goals, risked_goals, achievement_desc, career_status, university_name, speciality_name, date_finish_education, lead_experience_years, professionlevel_name, vac_days, lid_tribe_i_pernr, lid_1_lvl_i_pernr, lid_2_lvl_i_pernr, lid_3_lvl_i_pernr, lid_cluster_i_pernr, it_lid_cluster_i_pernr, cur_tribe_i_pernr]
Index: []

[0 rows x 54 columns]

In [24]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
grade_num,28020.0,1.030293e+01,2.072775e+00,7.0,9.000000e+00,1.000000e+01,1.200000e+01,16.0
age_y,28020.0,4.179204e+01,1.189042e+01,22.0,3.200000e+01,4.200000e+01,5.200000e+01,62.0
child_count,28020.0,8.753390e-01,9.967927e-01,0.0,0.000000e+00,1.000000e+00,2.000000e+00,3.0
family_status,28020.0,1.273269e+00,1.407872e+00,0.0,0.000000e+00,1.000000e+00,1.000000e+00,5.0
is_on_trial,28020.0,2.765882e-02,1.639962e-01,0.0,0.000000e+00,0.000000e+00,0.000000e+00,1.0
sber_los_cnt_days,28020.0,2.704837e+03,1.650953e+03,0.0,1.226000e+03,2.673000e+03,4.154000e+03,5624.0
is_parental_leave,28020.0,1.680942e-02,1.285591e-01,0.0,0.000000e+00,0.000000e+00,0.000000e+00,1.0
date_since_salary_change_last,28020.0,4.794772e+02,2.860160e+02,0.0,2.300000e+02,4.810000e+02,7.290000e+02,1050.0
po_i_pernr,28020.0,1.000060e+07,8.059139e+02,10000003.0,1.000016e+07,1.000033e+07,1.000078e+07,10004151.0
tribe_code,22666.0,5.009405e+03,5.116751e+00,5001.0,5.005000e+03,5.009000e+03,5.014000e+03,5020.0
cluster_code,22666.0,6.024620e+03,1.291385e+01,6001.0,6.014000e+03,6.023000e+03,6.037000e+03,6053.0
team_code,22666.0,7.084440e+03,4.614616e+01,7001.0,7.048000e+03,7.081000e+03,7.128000e+03,7164.0
mean_value_completion,28020.0,6.510839e-01,2.004103e-01,0.3,4.786000e-01,6.516000e-01,8.228250e-01,1.0
num_goals,28020.0,3.496788e+00,1.116836e+00,2.0,3.000000e+00,3.000000e+00,5.000000e+00,5.0
not_completed_goals,28020.0,1.190364e+00,9.004997e-01,0.0,1.000000e+00,1.000000e+00,2.000000e+00,3.0
risked_goals,28020.0,6.079229e-01,7.663802e-01,0.0,0.000000e+00,0.000000e+00,1.000000e+00,3.0
lead_experience_years,28020.0,1.230871e+00,3.586000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,25.0
vac_days,28020.0,1.401174e+01,8.369840e+00,0.0,7.000000e+00,1.400000e+01,2.100000e+01,28.0
lid_tribe_i_pernr,28020.0,8.089410e+06,3.931663e+06,0.0,1.000001e+07,1.000007e+07,1.000032e+07,10000983.0
lid_1_lvl_i_pernr,28020.0,1.000008e+07,8.195123e+01,10000003.0,1.000003e+07,1.000003e+07,1.000016e+07,10000243.0
lid_2_lvl_i_pernr,28020.0,1.000020e+07,2.052657e+02,10000003.0,1.000003e+07,1.000014e+07,1.000032e+07,10000983.0
lid_3_lvl_i_pernr,28020.0,1.000060e+07,8.059139e+02,10000003.0,1.000016e+07,1.000033e+07,1.000078e+07,10004151.0
lid_cluster_i_pernr,28020.0,8.089771e+06,3.931839e+06,0.0,1.000001e+07,1.000020e+07,1.000058e+07,10010966.0
it_lid_cluster_i_pernr,28020.0,8.089771e+06,3.931839e+06,0.0,1.000001e+07,1.000020e+07,1.000058e+07,10010966.0
cur_tribe_i_pernr,28020.0,8.089410e+06,3.931663e+06,0.0,1.000001e+07,1.000007e+07,1.000032e+07,10000983.0

In [14]:
pd.read_sql('''
    SELECT *
    FROM employees
    limit 2
''', con).T

,0,1
report_date,2025-10-31,2025-10-31
employee_id,10000001,10000004
grade_num,13,12
position_name,HR-специалист,Юрист
unit_id_tree,"[1063, 1103, 1107, 1108]","[1063, 1064, 1075, 1077]"
person_surname,Гришина,Поляков
person_name,Валерия,Евстафий
person_patronimics,Алексеевна,Федосеевич
gender,F,M
age_y,25,57
wrk_email,innokenti32@synthbank.ru,hariton1985@synthbank.ru
ext_email,innokenti32312@yandex.ru,hariton1985684@yandex.ru
employee_kipphn,+79478798403,+79904659703
child_count,1,1
family_status,1,0
is_on_trial,0,0
sber_los_cnt_days,2954,2852
is_parental_leave,0,0
all_skills,"[""1С"", ""Excel (продвинутый)"", ""Продажи B2B"", ""...","[""Продажи B2B"", ""Юридический английский"", ""МСФ..."
date_since_salary_change_last,445,215
po_i_pernr,10000145,10000323
fp_res,C,D
fp_comp,C,A
full_oshs_name,Блок Розничный Бизнес / Департамент Back-Offic...,Блок Розничный Бизнес / Центр Премиальных Клие...
all_succesors,"[""10000349""]","[""10002782"", ""10018361"", ""10007097""]"
children_gender,"[""M""]","[""M""]"
children_years,[0],[18]
lang_with_level,[],"[""Английский / A2""]"
tribe_name,Tribe SME Banking 17,Трайб Express Retail Lending
cluster_name,Кластер Онбординг,Кластер Выпуск карт Quantum
team_name,Team Sigma 98,Team Sud 83
tribe_code,5017.0,5014.0
cluster_code,6043.0,6037.0
team_code,7148.0,7128.0
all_goals_desc,"[""Запустить продукт X"", ""Сократить срок обрабо...","[""Привлечь клиентов сегмента B"", ""Сократить ср..."
mean_value_completion,0.7217,0.7301
num_goals,3,3
not_completed_goals,1,1
risked_goals,0,0
achievement_desc,"[""Выполнил план продаж на 120%"", ""Оптимизирова...","[""Оптимизировал процесс обработки заявок"", ""Вы..."
career_status,Закрыт,Не заполнено
university_name,МГУ им. М.В. Ломоносова,КФУ
speciality_name,Бухгалтерский учёт и аудит,Менеджмент
date_finish_education,2022-06-30,2004-06-30
lead_experience_years,0,0
professionlevel_name,Legal,Risk
vac_days,19,20
lid_tribe_i_pernr,10000145,10000134
lid_1_lvl_i_pernr,10000028,10000028
lid_2_lvl_i_pernr,10000145,10000134
lid_3_lvl_i_pernr,10000145,10000323
lid_cluster_i_pernr,10000145,10000323
it_lid_cluster_i_pernr,10000145,10000323
cur_tribe_i_pernr,10000145,10000134

In [17]:
pd.read_sql('''
-- 1. Самое распространенное мужское имя в банке
SELECT person_name, COUNT(*) as cnt
FROM employees
WHERE gender = 'M'
GROUP BY person_name
ORDER BY cnt DESC
LIMIT 1;
''', con)

  person_name  cnt
0  Варфоломей  115

In [ ]:
pd.read_sql('''
-- 3. Кто знает китайский язык?
SELECT *
FROM employees
WHERE lang_with_level LIKE '%Китайский%';
''', con).shape

,report_date,employee_id,grade_num,position_name,unit_id_tree,person_surname,person_name,person_patronimics,gender,age_y,...,lead_experience_years,professionlevel_name,vac_days,lid_tribe_i_pernr,lid_1_lvl_i_pernr,lid_2_lvl_i_pernr,lid_3_lvl_i_pernr,lid_cluster_i_pernr,it_lid_cluster_i_pernr,cur_tribe_i_pernr
0,2025-10-31,10000051,8,Data Scientist,"[1001, 1040, 1047, 1048]",Маслов,Артем,Данилович,M,26,...,0,QA,6,10000414,10000155,10000414,10000778,10000414,10000414,10000414
1,2025-10-31,10000060,12,Кредитный аналитик,"[1235, 1268, 1281, 1282]",Дорофеева,Таисия,Владиславовна,F,29,...,0,Marketing,16,10000049,10000049,10000049,10000049,10000049,10000049,10000049
2,2025-10-31,10000181,13,Руководитель отдела Gamma-77,"[1235, 1268, 1275, 1278]",Алексеев,Валерия,Витальевич,NaN,51,...,8,Management,25,10000049,10000049,10000049,10000181,10000049,10000049,10000049
3,2025-10-31,10000222,13,Старший операционист,"[1170, 1215, 1223, 1228]",Третьякова,Ангелина,Руслановна,F,52,...,0,Credit,24,10000410,10000243,10000410,10001594,10000793,10000793,10000410
4,2025-10-31,10000312,7,Андеррайтер,"[1115, 1138, 1139, 1140]",Петров,Савватий,Димитриевич,M,59,...,0,Legal,16,10000003,10000003,10000003,10000013,10000594,10000594,10000003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1289,2026-03-31,10021007,9,Ведущий специалист по кредитованию,"[1170, 1171, 1180, 1184]",Бирюков,Мокей,Валерианович,M,46,...,0,Risk,11,10000297,10000243,10000297,10000297,10000297,10000297,10000297
1290,2026-03-31,10021112,12,Scrum Master,"[1001, 1040, 1041, 1045]",Тетерин,Мечислав,Данилович,M,55,...,0,Architecture,16,0,10000155,10000195,10000195,0,0,0
1291,2026-03-31,10021162,7,Старший финансовый аналитик,"[1115, 1116, 1125, 1126]",Белов,Велимир,Александрович,M,49,...,0,Risk,7,10000037,10000003,10000037,10000037,10000037,10000037,10000037
1292,2026-03-31,10021171,13,Руководитель отдела Beta-13,"[1001, 1009, 1019, 1023]",Гордеева,Лукия,Егоровна,F,61,...,16,Management,9,10000385,10000155,10000385,10000385,10005905,10005905,10000385
1293,2026-03-31,10021437,7,Scrum Master,"[1001, 1024, 1025, 1026]",Пономарев,Ростислав,Аксёнович,M,46,...,3,Data,7,10000581,10000155,10000581,10002842,10000581,10000581,10000581

In [29]:
pd.read_sql('''
-- 4. выведи распределение по уровню владения английским языком
SELECT 
  value AS level,
  COUNT(*) AS cnt
FROM employees, json_each(lang_with_level)
WHERE json_valid(lang_with_level) 
  AND value LIKE 'Английский /%'
GROUP BY level;
''', con)

             level   cnt
0  Английский / A2  5126
1  Английский / B1  7302
2  Английский / B2  4909
3  Английский / C1  2546
4  Английский / C2  1185

In [31]:
df.tribe_name.unique()

<StringArray>
[          'Tribe SME Banking 17',   'Трайб Express Retail Lending',
      'Трайб Nova Compliance Ops',   'Трайб «Investment Solutions»',
   'Tribe Investment Solutions 4',      'Трайб Compliance Ops Core',
                              nan,        'Tribe Fraud Detection 6',
 'Tribe Back-Office Operations 7',           'Tribe SME Banking 19',
        'Трайб «Data Governance»',           'Трайб Unified Claims',
              'Tribe Mortgage 16',                 'Трайб «Claims»',
          'Трайб Loyalty Digital',   'Tribe Investment Solutions 2',
       'Tribe Web Engineering 18',        'Tribe Data Governance 3',
               'Трайб «Treasury»',           'Трайб «Core Banking»',
    'Трайб Vector Retail Lending']
Length: 21, dtype: str

In [ ]:
pd.read_sql('''
-- 5. покажи какими навыками в среднем обладают сотрудники трайба HR
-- (среднее = наиболее частые навыки)
SELECT value AS skill, COUNT(*) AS freq
FROM employees, json_each(all_skills)
WHERE json_valid(all_skills) 
  AND tribe_name LIKE '%Core Banking%'
GROUP BY skill
ORDER BY freq DESC;
''', con)

              skill  freq
0   Computer Vision   246
1        Kubernetes   241
2            Oracle   236
3      Коммуникации   224
4             CI/CD   223
..              ...   ...
58        Комплаенс     3
59             РСБУ     2
60     Андеррайтинг     2
61        Basel III     2
62               1С     2

[63 rows x 2 columns]

In [34]:
pd.read_sql('''
-- 7. Сотрудники за последние 4 квартала с самыми высокими оценками за результат
-- Предполагаем, что есть оценка fp_res = 'A' и дата отчёта report_date
WITH ranked AS (
  SELECT employee_id, fp_res, report_date,
         DENSE_RANK() OVER (PARTITION BY employee_id ORDER BY fp_res ASC) AS rnk
  FROM employees
  WHERE report_date >= date('now', '-12 months')  -- 4 квартала ~ 12 мес
    AND fp_res = 'A'
)
SELECT DISTINCT employee_id FROM ranked WHERE rnk = 1;
''', con)

     employee_id
0       10000018
1       10000043
2       10000045
3       10000060
4       10000102
...          ...
1276    10021447
1277    10021464
1278    10021469
1279    10021477
1280    10021499

[1281 rows x 1 columns]

In [ ]:
df.university_name.unique()

<StringArray>
[                    'МГУ им. М.В. Ломоносова',
                                         'КФУ',
 'Финансовый университет при Правительстве РФ',
                      'РЭУ им. Г.В. Плеханова',
                                        'МФТИ',
                                     'НИУ ВШЭ',
                                     'РАНХиГС',
                                        'УрФУ',
                       'МГТУ им. Н.Э. Баумана',
                                        'ИТМО',
                                       'МИСиС',
                                         'НГУ',
                                       'СПбГУ',
                                        'РУДН']
Length: 14, dtype: str

In [42]:
pd.read_sql('''
-- 9. Покажи сколько сотрудников имеют детей мужского пола в возрасте до 10 лет
SELECT COUNT(*)
FROM employees
WHERE EXISTS (
  SELECT 1 FROM json_each(children_gender) AS g,
              json_each(children_years) AS y
  WHERE g.value = 'M' AND y.value < 10 AND g.id = y.id
);
''', con)

   COUNT(*)
0      4484

In [45]:
df.speciality_name.unique()

<StringArray>
[         'Бухгалтерский учёт и аудит',                          'Менеджмент',
                       'Юриспруденция',                           'Маркетинг',
                    'Финансы и кредит',                           'Экономика',
                     'Банковское дело', 'Прикладная математика и информатика',
         'Информационная безопасность',                        'Data Science',
                  'Компьютерные науки',               'Программная инженерия']
Length: 12, dtype: str

In [47]:
pd.read_sql('''
-- 13. покажи долю сотрудников с экономическим образованием специальностью "экономист"
SELECT 1.0 * COUNT(*) / (SELECT COUNT(*) FROM employees) AS ratio
FROM employees
WHERE speciality_name LIKE '%Экономи%';
''', con)

      ratio
0  0.111206

In [48]:
df.career_status.unique()

<StringArray>
['Закрыт', 'Не заполнено', 'Открыт', nan]
Length: 4, dtype: str

In [51]:
df.career_status.unique()

<StringArray>
['Закрыт', 'Не заполнено', 'Открыт', nan]
Length: 4, dtype: str

In [52]:
pd.read_sql('''
SELECT 1.0 * COUNT(*) / (SELECT COUNT(*) FROM employees WHERE full_oshs_name LIKE '%Блок Риски и Комплаенс%') AS ratio
FROM employees
WHERE career_status = 'Открыт' AND full_oshs_name LIKE '%Блок Риски и Комплаенс%';
''', con)

      ratio
0  0.243853

In [53]:
pd.read_sql('''
-- 15. Выведи распределение по семейному положению сотрудников в банке
SELECT 
  CASE family_status
    WHEN 0 THEN 'Не женат/Не замужем'
    WHEN 1 THEN 'Женат/Замужем'
    WHEN 2 THEN 'Разведён(а)'
    ELSE 'Не указано'
  END AS status,
  COUNT(*) AS cnt
FROM employees
GROUP BY family_status;
''', con)

                status    cnt
0  Не женат/Не замужем   8659
1        Женат/Замужем  12779
2          Разведён(а)   2125
3           Не указано    496
4           Не указано   2645
5           Не указано   1316

In [58]:
df.position_name.unique()

<StringArray>
[                            'HR-специалист',
                                     'Юрист',
                     'Специалист комплаенса',
        'Ведущий специалист по кредитованию',
                       'Финансовый аналитик',
                        'Кредитный аналитик',
            'Ведущий специалист по продажам',
              'Руководитель отдела Alpha-53',
                             'Data Engineer',
             'Руководитель отдела Юпитер-84',
 ...
             'Руководитель отдела Сатурн-44',
               'Руководитель отдела Beta-29',
               'Руководитель отдела Alpha-3',
             'Руководитель отдела Нептун-53',
             'Руководитель отдела Юпитер-29',
             'Руководитель отдела Юпитер-86',
 'Руководитель отдела Поддержки Клиентов-46',
          'Руководитель отдела Pineapple-86',
              'Руководитель отдела Delta-83',
              'Руководитель отдела Mango-85']
Length: 213, dtype: str

In [ ]:
pd.read_sql('''
-- 17. покажи долю руководителей в банке
-- (руководители: lead_experience_years > 0 или должность содержит 'руководитель')
SELECT 1.0 * COUNT(*) / (SELECT COUNT(*) FROM employees) AS ratio
FROM employees
WHERE LOWER(position_name) LIKE '%руководи%' OR lead_experience_years > 0;
''', con)

      ratio   LOWER(position_name)
0  0.211884  Специалист комплаенса

In [169]:
df.report_date.min(), df.report_date.max()

('2025-10-31', '2026-03-31')

In [68]:
pd.read_sql('''
-- 18. покажи динамику изменения численности в блоке Риски и Комплаенс в 2025 году
SELECT strftime('%Y-%m', report_date) AS month, COUNT(*) AS cnt
FROM employees
WHERE full_oshs_name LIKE '%Блок Риски и Комплаенс%' AND strftime('%Y', report_date) = '2025'
GROUP BY month
ORDER BY month;
''', con)

     month  cnt
0  2025-10  580
1  2025-11  583
2  2025-12  575

In [70]:
pd.read_sql('''
-- 19. самый распространенный возраст сотрудников для каждого грейда
WITH ranked_ages AS (
  SELECT 
    grade_num,
    age_y,
    COUNT(*) AS cnt,
    RANK() OVER (PARTITION BY grade_num ORDER BY COUNT(*) DESC) AS rnk
  FROM employees
  GROUP BY grade_num, age_y
)
SELECT grade_num, age_y, cnt
FROM ranked_ages
WHERE rnk = 1
ORDER BY grade_num;
''', con)

   grade_num  age_y  cnt
0          7     23  135
1          8     62  127
2          9     27  152
3         10     52  119
4         11     32  170
5         12     26  143
6         13     55  176
7         14     55   46
8         15     50    5
9         16     49    1

In [71]:
pd.read_sql('''
-- 28. покажи долю сотрудников с процентом выполнения целей 75% в 4 квартале 2025
-- (mean_value_completion = 0.75)
SELECT 1.0 * COUNT(*) / (SELECT COUNT(*) FROM employees WHERE strftime('%Y', report_date) = '2025') AS ratio
FROM employees
WHERE mean_value_completion = 0.75 AND strftime('%Y', report_date) = '2025'
  AND strftime('%m', report_date) BETWEEN '10' AND '12';
''', con)

      ratio
0  0.000428

In [73]:
pd.read_sql('''
-- 47. Сколько сотрудников выше 11 грейда в команде Ивановой Марии?
-- (предполагаем, что Иванова Мария – руководитель, её команда = те, у кого lid_1_lvl_i_pernr = её employee_id)
SELECT COUNT(*)
FROM employees
WHERE lid_1_lvl_i_pernr = (SELECT employee_id FROM employees WHERE person_name = 'Мария' AND person_surname = 'Иванова')
  AND grade_num > 11;
''', con)

   COUNT(*)
0         0

In [77]:
pd.read_sql('''
-- 201. Все люди с дубликатами по имени и фамилии (каждая запись сотрудника + количество дублей)
SELECT 
  employee_id,
  person_surname,
  person_name,
  person_patronimics,
  tribe_code,
  COUNT(*) OVER (PARTITION BY person_surname, person_name) AS total_duplicates_global,
  COUNT(*) OVER (PARTITION BY person_surname, person_name, tribe_code) AS duplicates_in_tribe
FROM employees
WHERE (person_surname, person_name) IN (
    SELECT person_surname, person_name
    FROM employees
    GROUP BY person_surname, person_name
    HAVING COUNT(*) > 1
)
ORDER BY total_duplicates_global DESC, duplicates_in_tribe DESC;
''', con)

,employee_id,person_surname,person_name,person_patronimics,tribe_code,total_duplicates_global,duplicates_in_tribe
0,10015405,Горбунова,Полина,Игоревна,5008.0,18,6
1,10015405,Горбунова,Полина,Игоревна,5008.0,18,6
2,10015405,Горбунова,Полина,Игоревна,5008.0,18,6
3,10015405,Горбунова,Полина,Игоревна,5008.0,18,6
4,10015405,Горбунова,Полина,Игоревна,5008.0,18,6
...,...,...,...,...,...,...,...
27894,10021144,Щукин,Серафим,Владленович,5015.0,2,2
27895,10020945,Яковлева,Ирина,Ниловна,5007.0,2,2
27896,10020945,Яковлева,Ирина,Ниловна,5007.0,2,2
27897,10018537,Громов,Якуб,Гертрудович,5005.0,2,1
27898,10018537,Громов,Якуб,Гертрудович,5010.0,2,1

In [ ]:
pd.read_sql('''
''', con)

In [ ]:
pd.read_sql('''
''', con)

In [78]:
pd.read_sql('''
-- 51. Сотрудники какого грейда чаще всего получали повышенные оценки за результативность в прошлом году?
-- (повышенные = fp_res = 'A' или 'B')
SELECT grade_num, COUNT(*) AS cnt
FROM employees
WHERE fp_res IN ('A', 'B') AND strftime('%Y', report_date) = strftime('%Y', 'now', '-1 year')
GROUP BY grade_num
ORDER BY cnt DESC
LIMIT 1;
''', con)

   grade_num  cnt
0         11  907

In [80]:
df.employee_id.unique()

<StringArray>
['10000001', '10000004', '10000007', '10000018', '10000020', '10000032',
 '10000035', '10000036', '10000042', '10000043',
 ...
 '10021464', '10021469', '10021470', '10021474', '10021476', '10021477',
 '10021489', '10021491', '10021492', '10021499']
Length: 5000, dtype: str

In [81]:
pd.read_sql('''
-- 54. Сравни процент женатых сотрудников моей команды по месяцам с сентября прошлого года (current_user_id: 10021469)
WITH my_team AS (
  SELECT team_name FROM employees WHERE employee_id = 10021469
)
SELECT strftime('%Y-%m', report_date) AS month,
       1.0 * SUM(CASE WHEN family_status=1 THEN 1 ELSE 0 END) / COUNT(*) AS married_ratio
FROM employees e, my_team mt
WHERE e.team_name = mt.team_name
  AND report_date >= date('now', '-1 year', 'start of month', '+8 months') -- с сентября
GROUP BY month
ORDER BY month;
''', con)

     month  married_ratio
0  2025-12       0.428571
1  2026-01       0.428571
2  2026-02       0.428571
3  2026-03       0.466667

In [82]:
pd.read_sql('''
SELECT person_name, person_surname
FROM employees
WHERE employee_id = (SELECT lid_1_lvl_i_pernr FROM employees WHERE employee_id = 10021469);
''', con)

Empty DataFrame
Columns: [person_name, person_surname]
Index: []

In [163]:
df[df.employee_id.isin(df.lid_tribe_i_pernr.unique())].shape, \
df[df.employee_id.isin(df.lid_1_lvl_i_pernr.unique())].shape, \
df[df.employee_id.isin(df.lid_2_lvl_i_pernr.unique())].shape, \
df[df.employee_id.isin(df.lid_3_lvl_i_pernr.unique())].shape, \
df[df.employee_id.isin(df.lid_cluster_i_pernr.unique())].shape, \
df[df.employee_id.isin(df.it_lid_cluster_i_pernr.unique())].shape

((0, 54), (0, 54), (0, 54), (0, 54), (0, 54), (0, 54))

In [164]:
df[df.lid_tribe_i_pernr.isin(df.employee_id.unique())].shape, \
df[df.lid_1_lvl_i_pernr.isin(df.employee_id.unique())].shape, \
df[df.lid_2_lvl_i_pernr.isin(df.employee_id.unique())].shape, \
df[df.lid_3_lvl_i_pernr.isin(df.employee_id.unique())].shape, \
df[df.lid_cluster_i_pernr.isin(df.employee_id.unique())].shape, \
df[df.it_lid_cluster_i_pernr.isin(df.employee_id.unique())].shape

((0, 54), (0, 54), (0, 54), (0, 54), (0, 54), (0, 54))

In [87]:
pd.read_sql('''
-- 76. Сколько команд имеют численность более 15 человек выведи число?
SELECT COUNT(*) AS teams_with_more_than_15
FROM (
    SELECT team_name
    FROM employees
    WHERE team_name IS NOT NULL
    GROUP BY team_name
    HAVING COUNT(*) > 15
) AS large_teams;
''', con)

   teams_with_more_than_15
0                      158

In [88]:
pd.read_sql('''
-- 80. Сколько сотрудников с грейдом выше 13 имеют оценку за результативность ниже 3
-- (оценка ниже 3 – предположим fp_res = 'D' или 'E')
SELECT COUNT(*)
FROM employees
WHERE grade_num > 13 AND fp_res IN ('D', 'E');
''', con)

   COUNT(*)
0       140

In [89]:
pd.read_sql('''
-- 90. Выведи распределение грейдов по интервалам возраста для сотрудников кампании
SELECT 
  CASE 
    WHEN age_y < 25 THEN '<25'
    WHEN age_y BETWEEN 25 AND 35 THEN '25-35'
    WHEN age_y BETWEEN 36 AND 45 THEN '36-45'
    WHEN age_y BETWEEN 46 AND 55 THEN '46-55'
    ELSE '55+'
  END AS age_group,
  grade_num,
  COUNT(*) AS cnt
FROM employees
GROUP BY age_group, grade_num
ORDER BY age_group, grade_num;
''', con)

   age_group  grade_num   cnt
0      25-35          7   976
1      25-35          8   980
2      25-35          9  1070
3      25-35         10   925
4      25-35         11  1277
5      25-35         12  1212
6      25-35         13  1226
7      25-35         14   153
8      25-35         15     4
9      36-45          7   749
10     36-45          8   893
11     36-45          9   956
12     36-45         10   867
13     36-45         11  1049
14     36-45         12   974
15     36-45         13  1153
16     36-45         14   133
17     36-45         15     2
18     46-55          7   813
19     46-55          8   760
20     46-55          9   757
21     46-55         10   824
22     46-55         11  1093
23     46-55         12   977
24     46-55         13  1093
25     46-55         14   215
26     46-55         15     9
27     46-55         16     1
28       55+          7   621
29       55+          8   580
30       55+          9   598
31       55+         10   560
32       55+         11   716
33       55+         12   761
34       55+         13   818
35       55+         14   124
36       55+         15     4
37       <25          7   313
38       <25          8   289
39       <25          9   240
40       <25         10   248
41       <25         11   356
42       <25         12   273
43       <25         13   339
44       <25         14    39

In [90]:
pd.read_sql('''
-- 91. Выведи первого в лексикографическом порядке сотрудника для каждого грейда
-- (лексикографический порядок по полному имени)
SELECT grade_num, MIN(person_surname || ' ' || person_name) AS first_employee
FROM employees
GROUP BY grade_num;
''', con)

   grade_num       first_employee
0          7        Абрамов Демид
1          8      Абрамов Соломон
2          9        Абрамов Демид
3         10       Абрамов Эрнест
4         11      Абрамов Савелий
5         12       Абрамов Кузьма
6         13       Абрамов Андрон
7         14        Авдеева Фаина
8         15  Александрова Ксения
9         16        Козлов Зосима

In [91]:
pd.read_sql('''
-- 110. Есть ли корреляция между оценкой результативности и оценкой ценностей?
-- (преобразуем буквы в числа A=5,B=4,C=3,D=2)
WITH mapped AS (
  SELECT 
    CASE fp_res WHEN 'A' THEN 5 WHEN 'B' THEN 4 WHEN 'C' THEN 3 ELSE 2 END AS res_num,
    CASE fp_comp WHEN 'A' THEN 5 WHEN 'B' THEN 4 WHEN 'C' THEN 3 ELSE 2 END AS comp_num
  FROM employees
)
SELECT (AVG(res_num * comp_num) - AVG(res_num)*AVG(comp_num)) /
       (SQRT(AVG(res_num*res_num) - AVG(res_num)*AVG(res_num)) *
        SQRT(AVG(comp_num*comp_num) - AVG(comp_num)*AVG(comp_num))) AS correlation
FROM mapped;
''', con)

   correlation
0     0.001088

In [92]:
pd.read_sql('''
-- 112. Пришли почту сотрудника, у которого стаж 5 лет и он мужчина
SELECT wrk_email
FROM employees
WHERE (sber_los_cnt_days / 365.0) = 5 AND gender = 'M'
LIMIT 1;
''', con)

                 wrk_email
0  marija2007@synthbank.ru

In [93]:
pd.read_sql('''
-- 127. Можно ли выделить группу сотрудников, у которых более 2000 дней стажа, но при этом грейд ниже среднего?
SELECT employee_id, sber_los_cnt_days, grade_num
FROM employees
WHERE sber_los_cnt_days > 2000
  AND grade_num < (SELECT AVG(grade_num) FROM employees);
''', con)

     employee_id  sber_los_cnt_days  grade_num
0       10000018               2048          9
1       10000035               5266          8
2       10000036               4765          8
3       10000042               4603         10
4       10000051               2439          8
...          ...                ...        ...
8638    10019949               4846          9
8639    10019954               4798          8
8640    10019962               3983          8
8641    10019977               4474          8
8642    10019999               3306          8

[8643 rows x 3 columns]

In [94]:
pd.read_sql('''
-- 130. Сколько сотрудников мужчин в декрете?
SELECT COUNT(*) FROM employees WHERE gender='M' AND is_parental_leave=1;
''', con)

   COUNT(*)
0         0

In [96]:
df.is_parental_leave.unique()

array([0, 1])

In [ ]:
pd.read_sql('''
-- 131. Выведи команды, где больше 10% сотрудников на испытательном сроке?
SELECT team_name, 1.0 * SUM(is_on_trial) / COUNT(*) AS trial_ratio
FROM employees
GROUP BY team_name
HAVING trial_ratio > 0.1;
''', con)

                       team_name  trial_ratio
0       Команда Lychee-Сатурн-12     0.104348
1  Команда Nord-Сопровождения-86     0.116279

In [105]:
pd.read_sql('''
-- 132. В каких командах самый высокий средний возраст сотрудников?
SELECT team_name, AVG(age_y) AS avg_age
FROM employees
GROUP BY team_name
ORDER BY avg_age DESC
--LIMIT 10;
''', con)

                    team_name    avg_age
0     Команда Delta Аналитики  47.815385
1        Команда Zeta-Alpha-9  47.716981
2      Команда Lemon-Gamma-87  47.466667
3                Team Zero 15  47.361111
4               Team Apple 12  47.118280
..                        ...        ...
154  Команда Prime Automation  36.049296
155             Команда Sigma  35.960784
156  Команда Core Engineering  35.915888
157        Команда Kiwi South  35.560440
158  Команда Papaya-Сатурн-86  31.979167

[159 rows x 2 columns]

In [110]:
df[['children_gender', 'children_years']]

       children_gender children_years
0                ["M"]            [0]
1                ["M"]           [18]
2           ["F", "F"]         [0, 9]
3                ["M"]            [6]
4      ["M", "F", "M"]      [3, 8, 7]
...                ...            ...
28015       ["F", "F"]        [10, 8]
28016       ["F", "F"]         [3, 0]
28017               []             []
28018               []             []
28019       ["F", "M"]        [15, 0]

[28020 rows x 2 columns]

In [ ]:
pd.read_sql('''
-- 202. Проверь, есть ли тезки по фамилии и имени, у которых разный грейд
SELECT 
  person_surname,
  person_name,
  group_concat(DISTINCT grade_num) AS different_grades,
  COUNT(*) AS total_employees,
  COUNT(DISTINCT grade_num) AS distinct_grades_count
FROM employees
WHERE person_surname IS NOT NULL AND person_name IS NOT NULL
GROUP BY person_surname, person_name
HAVING COUNT(DISTINCT grade_num) > 1
ORDER BY distinct_grades_count DESC, total_emplмoyees DESC;
''', con)

,person_surname,person_name,different_grades,total_employees,distinct_grades_count
0,Горшков,Захар,"13,8,12",18,3
1,Денисова,Марина,"10,12,11",17,3
2,Сысоев,Авксентий,"12,9,13",12,3
3,Поляков,Кир,"14,13,15",12,3
4,Гурьева,Майя,"12,10,13",12,3
...,...,...,...,...,...
248,Кабанов,Елизар,"8,9",3,2
249,Иванова,Марина,"9,10",3,2
250,Иванова,Виктория,"13,14",3,2
251,Константинов,Иларион,"8,9",2,2
252,Герасимова,Прасковья,"8,9",2,2

In [134]:
pd.read_sql('''
-- 142. выведи возраст детей Горшкова Захара который 12 грейда
SELECT children_years, person_surname, grade_num
FROM employees
WHERE person_name='Захар' AND person_surname='Горшков' AND grade_num=12;
''', con).head(50)

  children_years person_surname  grade_num
0        [15, 6]        Горшков         12
1        [15, 6]        Горшков         12
2        [15, 6]        Горшков         12
3        [15, 6]        Горшков         12
4        [15, 6]        Горшков         12
5        [15, 6]        Горшков         12

In [136]:
pd.read_sql('''
-- 146. выведи самого молодого сотрудника с самым высоким грейдом
-- (сначала отбираем максимальный грейд, затем среди них минимальный возраст)
SELECT age_y, *
FROM employees
WHERE grade_num = (SELECT MAX(grade_num) FROM employees)
ORDER BY age_y ASC
LIMIT 1;
''', con)

,age_y,report_date,employee_id,grade_num,position_name,unit_id_tree,person_surname,person_name,person_patronimics,gender,...,lead_experience_years,professionlevel_name,vac_days,lid_tribe_i_pernr,lid_1_lvl_i_pernr,lid_2_lvl_i_pernr,lid_3_lvl_i_pernr,lid_cluster_i_pernr,it_lid_cluster_i_pernr,cur_tribe_i_pernr
0,49,2026-03-31,10000073,16,Руководитель отдела Alpha-3,"[1235, 1236, 1246, 1248]",Козлов,Зосима,Давидович,M,...,17,Management,4,10000073,10000049,10000073,10000073,10000073,10000073,10000073

In [138]:
pd.read_sql('''
-- 162. в какой команде больше всего сотрудников в отпуске
SELECT team_name, COUNT(*) AS cnt
FROM employees
WHERE vac_days > 0
  AND team_name IS NOT NULL
GROUP BY team_name
ORDER BY cnt DESC
LIMIT 1;
''', con)

               team_name  cnt
0  Команда Zero-Gamma-32  428

In [143]:
df.cluster_name.unique()
df.full_oshs_name.unique()

df[df.cluster_name == 'Кластер Верификация'][['cluster_name', 'full_oshs_name']]

              cluster_name                                     full_oshs_name
15     Кластер Верификация  Блок Розничный Бизнес / Центр Премиальных Клие...
134    Кластер Верификация  Блок Розничный Бизнес / Центр Премиальных Клие...
157    Кластер Верификация  Блок Розничный Бизнес / Центр Премиальных Клие...
189    Кластер Верификация  Блок Розничный Бизнес / Центр Премиальных Клие...
247    Кластер Верификация  Блок Розничный Бизнес / Центр Премиальных Клие...
...                    ...                                                ...
27910  Кластер Верификация  Блок Розничный Бизнес / Центр Премиальных Клие...
27912  Кластер Верификация  Блок Розничный Бизнес / Центр Премиальных Клие...
27921  Кластер Верификация  Блок Розничный Бизнес / Центр Премиальных Клие...
27929  Кластер Верификация  Блок Розничный Бизнес / Центр Премиальных Клие...
27992  Кластер Верификация  Блок Розничный Бизнес / Центр Премиальных Клие...

[907 rows x 2 columns]

In [144]:
pd.read_sql('''
-- 163. приведи график распределения мужчин и женщин в Блоке Розничный Бизнес и кластере верификация
SELECT 
  'Блок Розничный Бизнес' AS division,
  gender,
  COUNT(*) AS cnt
FROM employees
WHERE full_oshs_name LIKE '%Розничный Бизнес%'
GROUP BY gender
UNION ALL
SELECT 
  'Кластер Core Banking',
  gender,
  COUNT(*)
FROM employees
WHERE cluster_name LIKE '%Верификация%'
GROUP BY gender;
''', con)

                division gender   cnt
0  Блок Розничный Бизнес    NaN   172
1  Блок Розничный Бизнес      F  3777
2  Блок Розничный Бизнес      M  4885
3   Кластер Core Banking    NaN    18
4   Кластер Core Banking      F   340
5   Кластер Core Banking      M   549

In [146]:
pd.read_sql('''
-- 175. Покажи самый популярный иностранный язык, которым владеют сотрудники женского пола
SELECT value AS language, COUNT(*) AS cnt
FROM employees, json_each(lang_with_level)
WHERE gender = 'F'
  AND json_valid(lang_with_level) = 1
  AND value NOT LIKE '%Русский%'
GROUP BY language
ORDER BY cnt DESC
LIMIT 1;
''', con)

          language   cnt
0  Английский / B1  3395

In [ ]:
df.position_name

<StringArray>
[                            'HR-специалист',
                                     'Юрист',
                     'Специалист комплаенса',
        'Ведущий специалист по кредитованию',
                       'Финансовый аналитик',
                        'Кредитный аналитик',
            'Ведущий специалист по продажам',
              'Руководитель отдела Alpha-53',
                             'Data Engineer',
             'Руководитель отдела Юпитер-84',
 ...
             'Руководитель отдела Сатурн-44',
               'Руководитель отдела Beta-29',
               'Руководитель отдела Alpha-3',
             'Руководитель отдела Нептун-53',
             'Руководитель отдела Юпитер-29',
             'Руководитель отдела Юпитер-86',
 'Руководитель отдела Поддержки Клиентов-46',
          'Руководитель отдела Pineapple-86',
              'Руководитель отдела Delta-83',
              'Руководитель отдела Mango-85']
Length: 213, dtype: str

In [156]:
pd.read_sql('''
-- 183. Какие сотрудники, занимающие должность руководителя отдела, закончили образование по направлению 'Финансы и кредит'?
SELECT *
FROM employees
WHERE position_name LIKE '%Руководитель отдела%' AND speciality_name LIKE '%Финансы и кредит%';
''', con)

,report_date,employee_id,grade_num,position_name,unit_id_tree,person_surname,person_name,person_patronimics,gender,age_y,...,lead_experience_years,professionlevel_name,vac_days,lid_tribe_i_pernr,lid_1_lvl_i_pernr,lid_2_lvl_i_pernr,lid_3_lvl_i_pernr,lid_cluster_i_pernr,it_lid_cluster_i_pernr,cur_tribe_i_pernr
0,2025-10-31,10000275,14,Руководитель отдела Сопровождения-48,"[1115, 1138, 1139, 1143]",Бобров,Федосий,Теймуразович,M,46,...,19,Management,13,10000003,10000003,10000003,10000013,10000013,10000013,10000003
1,2025-10-31,10000370,14,Руководитель отдела Сопровождения-37,"[1063, 1084, 1098, 1099]",Петухова,Пелагея,Феликсовна,F,49,...,10,Management,24,10000028,10000028,10000028,10000185,10000047,10000047,10000028
2,2025-10-31,10000844,11,Руководитель отдела Нептун-44,"[1063, 1084, 1085, 1086]",Михеева,Иванна,Геннадиевна,F,61,...,20,Management,19,0,10000028,10000028,10000240,0,0,0
3,2025-10-31,10001244,11,Руководитель отдела Alpha-72,"[1115, 1138, 1145, 1148]",Уварова,Ангелина,Архиповна,F,39,...,5,Management,25,10000003,10000003,10000003,10000003,10000594,10000594,10000003
4,2025-10-31,10001665,14,Руководитель отдела Меркурий-60,"[1170, 1199, 1206, 1207]",Кондратьева,Ангелина,Дмитриевна,F,36,...,6,Management,11,10000860,10000243,10000243,10001665,10001171,10001171,10000860
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,2026-03-31,10018728,12,Руководитель отдела Сопровождения-85,"[1063, 1103, 1111, 1113]",Фомина,Олимпиада,Ждановна,F,59,...,25,Management,6,0,10000028,10000145,10000799,0,0,0
327,2026-03-31,10019511,14,Руководитель отдела Mango-6,"[1115, 1130, 1135, 1137]",Костина,Нонна,Болеславовна,F,32,...,6,Management,19,0,10000003,10000417,10000417,0,0,0
328,2026-03-31,10019714,14,Руководитель отдела Alpha-24,"[1063, 1103, 1107, 1108]",Архипов,Селиверст,Васильевич,M,25,...,1,Management,17,10000145,10000028,10000145,10000145,10000145,10000145,10000145
329,2026-03-31,10020280,13,Руководитель отдела Сопровождения-48,"[1115, 1138, 1139, 1143]",Князев,Данила,Ермилович,M,49,...,2,Management,19,10000003,10000003,10000003,10000013,10000013,10000013,10000003
330,2026-03-31,10020886,12,Руководитель отдела Разработки-46,"[1235, 1268, 1275, 1276]",Емельянов,Никандр,Аксёнович,M,46,...,15,Management,5,10000049,10000049,10000049,10000181,10000049,10000049,10000049

In [ ]:
pd.read_sql('''
-- 185. кто нибудь вышел из декрета за последний квартал в моей команде? (current_user_id: 10021469)
-- (выход из декрета = is_parental_leave изменился с 1 на 0, нужна история)
WITH my_team AS (
  SELECT team_name FROM employees WHERE employee_id = 10021469
)
SELECT DISTINCT e.employee_id
FROM employees e, my_team mt
WHERE e.team_name = mt.team_name
  AND e.is_parental_leave = 0
  AND EXISTS (
    SELECT 1 FROM employees h 
    WHERE h.employee_id = e.employee_id AND h.report_date >= date('now', '-3 months')
      AND h.is_parental_leave = 1
  );''', con)

Empty DataFrame
Columns: [employee_id]
Index: []